###############################################################################
# Created by write_sdc
###############################################################################
current_design ALU
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name clk -period 30.0000 [get_ports {clk}]
set_clock_transition 0.1500 [get_clocks {clk}]
set_clock_uncertainty 0.2500 clk
set_propagated_clock [get_clocks {clk}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {A[0]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {A[10]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {A[11]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {A[12]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {A[13]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {A[14]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {A[15]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {A[16]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {A[17]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {A[18]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {A[19]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {A[1]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {A[20]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {A[21]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {A[22]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {A[23]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {A[24]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {A[25]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {A[26]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {A[27]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {A[28]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {A[29]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {A[2]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {A[30]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {A[31]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {A[3]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {A[4]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {A[5]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {A[6]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {A[7]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {A[8]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {A[9]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {B[0]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {B[10]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {B[11]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {B[12]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {B[13]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {B[14]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {B[15]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {B[16]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {B[17]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {B[18]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {B[19]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {B[1]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {B[20]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {B[21]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {B[22]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {B[23]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {B[24]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {B[25]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {B[26]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {B[27]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {B[28]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {B[29]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {B[2]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {B[30]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {B[31]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {B[3]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {B[4]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {B[5]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {B[6]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {B[7]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {B[8]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {B[9]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {opcode[0]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {opcode[1]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {opcode[2]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {opcode[3]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {opcode[4]}]
set_input_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {reset}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {borrow}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {carry}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {div_zero}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {negative}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {overflow}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[0]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[10]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[11]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[12]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[13]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[14]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[15]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[16]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[17]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[18]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[19]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[1]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[20]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[21]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[22]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[23]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[24]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[25]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[26]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[27]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[28]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[29]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[2]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[30]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[31]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[32]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[33]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[34]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[35]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[36]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[37]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[38]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[39]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[3]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[40]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[41]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[42]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[43]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[44]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[45]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[46]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[47]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[48]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[49]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[4]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[50]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[51]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[52]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[53]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[54]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[55]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[56]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[57]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[58]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[59]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[5]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[60]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[61]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[62]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[63]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[6]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[7]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[8]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {product[9]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {quotient[0]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {quotient[10]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {quotient[11]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {quotient[12]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {quotient[13]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {quotient[14]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {quotient[15]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {quotient[16]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {quotient[17]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {quotient[18]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {quotient[19]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {quotient[1]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {quotient[20]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {quotient[21]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {quotient[22]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {quotient[23]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {quotient[24]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {quotient[25]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {quotient[26]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {quotient[27]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {quotient[28]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {quotient[29]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {quotient[2]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {quotient[30]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {quotient[31]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {quotient[3]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {quotient[4]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {quotient[5]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {quotient[6]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {quotient[7]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {quotient[8]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {quotient[9]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {remainder[0]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {remainder[10]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {remainder[11]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {remainder[12]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {remainder[13]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {remainder[14]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {remainder[15]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {remainder[16]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {remainder[17]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {remainder[18]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {remainder[19]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {remainder[1]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {remainder[20]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {remainder[21]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {remainder[22]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {remainder[23]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {remainder[24]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {remainder[25]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {remainder[26]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {remainder[27]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {remainder[28]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {remainder[29]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {remainder[2]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {remainder[30]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {remainder[31]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {remainder[3]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {remainder[4]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {remainder[5]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {remainder[6]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {remainder[7]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {remainder[8]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {remainder[9]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {result[0]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {result[10]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {result[11]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {result[12]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {result[13]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {result[14]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {result[15]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {result[16]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {result[17]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {result[18]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {result[19]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {result[1]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {result[20]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {result[21]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {result[22]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {result[23]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {result[24]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {result[25]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {result[26]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {result[27]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {result[28]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {result[29]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {result[2]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {result[30]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {result[31]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {result[3]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {result[4]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {result[5]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {result[6]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {result[7]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {result[8]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {result[9]}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {valid}]
set_output_delay 6.0000 -clock [get_clocks {clk}] -add_delay [get_ports {zero}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0334 [get_ports {borrow}]
set_load -pin_load 0.0334 [get_ports {carry}]
set_load -pin_load 0.0334 [get_ports {div_zero}]
set_load -pin_load 0.0334 [get_ports {negative}]
set_load -pin_load 0.0334 [get_ports {overflow}]
set_load -pin_load 0.0334 [get_ports {valid}]
set_load -pin_load 0.0334 [get_ports {zero}]
set_load -pin_load 0.0334 [get_ports {product[63]}]
set_load -pin_load 0.0334 [get_ports {product[62]}]
set_load -pin_load 0.0334 [get_ports {product[61]}]
set_load -pin_load 0.0334 [get_ports {product[60]}]
set_load -pin_load 0.0334 [get_ports {product[59]}]
set_load -pin_load 0.0334 [get_ports {product[58]}]
set_load -pin_load 0.0334 [get_ports {product[57]}]
set_load -pin_load 0.0334 [get_ports {product[56]}]
set_load -pin_load 0.0334 [get_ports {product[55]}]
set_load -pin_load 0.0334 [get_ports {product[54]}]
set_load -pin_load 0.0334 [get_ports {product[53]}]
set_load -pin_load 0.0334 [get_ports {product[52]}]
set_load -pin_load 0.0334 [get_ports {product[51]}]
set_load -pin_load 0.0334 [get_ports {product[50]}]
set_load -pin_load 0.0334 [get_ports {product[49]}]
set_load -pin_load 0.0334 [get_ports {product[48]}]
set_load -pin_load 0.0334 [get_ports {product[47]}]
set_load -pin_load 0.0334 [get_ports {product[46]}]
set_load -pin_load 0.0334 [get_ports {product[45]}]
set_load -pin_load 0.0334 [get_ports {product[44]}]
set_load -pin_load 0.0334 [get_ports {product[43]}]
set_load -pin_load 0.0334 [get_ports {product[42]}]
set_load -pin_load 0.0334 [get_ports {product[41]}]
set_load -pin_load 0.0334 [get_ports {product[40]}]
set_load -pin_load 0.0334 [get_ports {product[39]}]
set_load -pin_load 0.0334 [get_ports {product[38]}]
set_load -pin_load 0.0334 [get_ports {product[37]}]
set_load -pin_load 0.0334 [get_ports {product[36]}]
set_load -pin_load 0.0334 [get_ports {product[35]}]
set_load -pin_load 0.0334 [get_ports {product[34]}]
set_load -pin_load 0.0334 [get_ports {product[33]}]
set_load -pin_load 0.0334 [get_ports {product[32]}]
set_load -pin_load 0.0334 [get_ports {product[31]}]
set_load -pin_load 0.0334 [get_ports {product[30]}]
set_load -pin_load 0.0334 [get_ports {product[29]}]
set_load -pin_load 0.0334 [get_ports {product[28]}]
set_load -pin_load 0.0334 [get_ports {product[27]}]
set_load -pin_load 0.0334 [get_ports {product[26]}]
set_load -pin_load 0.0334 [get_ports {product[25]}]
set_load -pin_load 0.0334 [get_ports {product[24]}]
set_load -pin_load 0.0334 [get_ports {product[23]}]
set_load -pin_load 0.0334 [get_ports {product[22]}]
set_load -pin_load 0.0334 [get_ports {product[21]}]
set_load -pin_load 0.0334 [get_ports {product[20]}]
set_load -pin_load 0.0334 [get_ports {product[19]}]
set_load -pin_load 0.0334 [get_ports {product[18]}]
set_load -pin_load 0.0334 [get_ports {product[17]}]
set_load -pin_load 0.0334 [get_ports {product[16]}]
set_load -pin_load 0.0334 [get_ports {product[15]}]
set_load -pin_load 0.0334 [get_ports {product[14]}]
set_load -pin_load 0.0334 [get_ports {product[13]}]
set_load -pin_load 0.0334 [get_ports {product[12]}]
set_load -pin_load 0.0334 [get_ports {product[11]}]
set_load -pin_load 0.0334 [get_ports {product[10]}]
set_load -pin_load 0.0334 [get_ports {product[9]}]
set_load -pin_load 0.0334 [get_ports {product[8]}]
set_load -pin_load 0.0334 [get_ports {product[7]}]
set_load -pin_load 0.0334 [get_ports {product[6]}]
set_load -pin_load 0.0334 [get_ports {product[5]}]
set_load -pin_load 0.0334 [get_ports {product[4]}]
set_load -pin_load 0.0334 [get_ports {product[3]}]
set_load -pin_load 0.0334 [get_ports {product[2]}]
set_load -pin_load 0.0334 [get_ports {product[1]}]
set_load -pin_load 0.0334 [get_ports {product[0]}]
set_load -pin_load 0.0334 [get_ports {quotient[31]}]
set_load -pin_load 0.0334 [get_ports {quotient[30]}]
set_load -pin_load 0.0334 [get_ports {quotient[29]}]
set_load -pin_load 0.0334 [get_ports {quotient[28]}]
set_load -pin_load 0.0334 [get_ports {quotient[27]}]
set_load -pin_load 0.0334 [get_ports {quotient[26]}]
set_load -pin_load 0.0334 [get_ports {quotient[25]}]
set_load -pin_load 0.0334 [get_ports {quotient[24]}]
set_load -pin_load 0.0334 [get_ports {quotient[23]}]
set_load -pin_load 0.0334 [get_ports {quotient[22]}]
set_load -pin_load 0.0334 [get_ports {quotient[21]}]
set_load -pin_load 0.0334 [get_ports {quotient[20]}]
set_load -pin_load 0.0334 [get_ports {quotient[19]}]
set_load -pin_load 0.0334 [get_ports {quotient[18]}]
set_load -pin_load 0.0334 [get_ports {quotient[17]}]
set_load -pin_load 0.0334 [get_ports {quotient[16]}]
set_load -pin_load 0.0334 [get_ports {quotient[15]}]
set_load -pin_load 0.0334 [get_ports {quotient[14]}]
set_load -pin_load 0.0334 [get_ports {quotient[13]}]
set_load -pin_load 0.0334 [get_ports {quotient[12]}]
set_load -pin_load 0.0334 [get_ports {quotient[11]}]
set_load -pin_load 0.0334 [get_ports {quotient[10]}]
set_load -pin_load 0.0334 [get_ports {quotient[9]}]
set_load -pin_load 0.0334 [get_ports {quotient[8]}]
set_load -pin_load 0.0334 [get_ports {quotient[7]}]
set_load -pin_load 0.0334 [get_ports {quotient[6]}]
set_load -pin_load 0.0334 [get_ports {quotient[5]}]
set_load -pin_load 0.0334 [get_ports {quotient[4]}]
set_load -pin_load 0.0334 [get_ports {quotient[3]}]
set_load -pin_load 0.0334 [get_ports {quotient[2]}]
set_load -pin_load 0.0334 [get_ports {quotient[1]}]
set_load -pin_load 0.0334 [get_ports {quotient[0]}]
set_load -pin_load 0.0334 [get_ports {remainder[31]}]
set_load -pin_load 0.0334 [get_ports {remainder[30]}]
set_load -pin_load 0.0334 [get_ports {remainder[29]}]
set_load -pin_load 0.0334 [get_ports {remainder[28]}]
set_load -pin_load 0.0334 [get_ports {remainder[27]}]
set_load -pin_load 0.0334 [get_ports {remainder[26]}]
set_load -pin_load 0.0334 [get_ports {remainder[25]}]
set_load -pin_load 0.0334 [get_ports {remainder[24]}]
set_load -pin_load 0.0334 [get_ports {remainder[23]}]
set_load -pin_load 0.0334 [get_ports {remainder[22]}]
set_load -pin_load 0.0334 [get_ports {remainder[21]}]
set_load -pin_load 0.0334 [get_ports {remainder[20]}]
set_load -pin_load 0.0334 [get_ports {remainder[19]}]
set_load -pin_load 0.0334 [get_ports {remainder[18]}]
set_load -pin_load 0.0334 [get_ports {remainder[17]}]
set_load -pin_load 0.0334 [get_ports {remainder[16]}]
set_load -pin_load 0.0334 [get_ports {remainder[15]}]
set_load -pin_load 0.0334 [get_ports {remainder[14]}]
set_load -pin_load 0.0334 [get_ports {remainder[13]}]
set_load -pin_load 0.0334 [get_ports {remainder[12]}]
set_load -pin_load 0.0334 [get_ports {remainder[11]}]
set_load -pin_load 0.0334 [get_ports {remainder[10]}]
set_load -pin_load 0.0334 [get_ports {remainder[9]}]
set_load -pin_load 0.0334 [get_ports {remainder[8]}]
set_load -pin_load 0.0334 [get_ports {remainder[7]}]
set_load -pin_load 0.0334 [get_ports {remainder[6]}]
set_load -pin_load 0.0334 [get_ports {remainder[5]}]
set_load -pin_load 0.0334 [get_ports {remainder[4]}]
set_load -pin_load 0.0334 [get_ports {remainder[3]}]
set_load -pin_load 0.0334 [get_ports {remainder[2]}]
set_load -pin_load 0.0334 [get_ports {remainder[1]}]
set_load -pin_load 0.0334 [get_ports {remainder[0]}]
set_load -pin_load 0.0334 [get_ports {result[31]}]
set_load -pin_load 0.0334 [get_ports {result[30]}]
set_load -pin_load 0.0334 [get_ports {result[29]}]
set_load -pin_load 0.0334 [get_ports {result[28]}]
set_load -pin_load 0.0334 [get_ports {result[27]}]
set_load -pin_load 0.0334 [get_ports {result[26]}]
set_load -pin_load 0.0334 [get_ports {result[25]}]
set_load -pin_load 0.0334 [get_ports {result[24]}]
set_load -pin_load 0.0334 [get_ports {result[23]}]
set_load -pin_load 0.0334 [get_ports {result[22]}]
set_load -pin_load 0.0334 [get_ports {result[21]}]
set_load -pin_load 0.0334 [get_ports {result[20]}]
set_load -pin_load 0.0334 [get_ports {result[19]}]
set_load -pin_load 0.0334 [get_ports {result[18]}]
set_load -pin_load 0.0334 [get_ports {result[17]}]
set_load -pin_load 0.0334 [get_ports {result[16]}]
set_load -pin_load 0.0334 [get_ports {result[15]}]
set_load -pin_load 0.0334 [get_ports {result[14]}]
set_load -pin_load 0.0334 [get_ports {result[13]}]
set_load -pin_load 0.0334 [get_ports {result[12]}]
set_load -pin_load 0.0334 [get_ports {result[11]}]
set_load -pin_load 0.0334 [get_ports {result[10]}]
set_load -pin_load 0.0334 [get_ports {result[9]}]
set_load -pin_load 0.0334 [get_ports {result[8]}]
set_load -pin_load 0.0334 [get_ports {result[7]}]
set_load -pin_load 0.0334 [get_ports {result[6]}]
set_load -pin_load 0.0334 [get_ports {result[5]}]
set_load -pin_load 0.0334 [get_ports {result[4]}]
set_load -pin_load 0.0334 [get_ports {result[3]}]
set_load -pin_load 0.0334 [get_ports {result[2]}]
set_load -pin_load 0.0334 [get_ports {result[1]}]
set_load -pin_load 0.0334 [get_ports {result[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {clk}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {reset}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A[31]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A[30]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A[29]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A[28]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A[27]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A[26]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A[25]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A[24]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A[23]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A[22]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A[21]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A[20]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A[19]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A[18]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A[17]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A[16]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {B[31]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {B[30]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {B[29]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {B[28]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {B[27]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {B[26]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {B[25]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {B[24]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {B[23]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {B[22]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {B[21]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {B[20]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {B[19]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {B[18]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {B[17]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {B[16]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {B[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {B[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {B[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {B[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {B[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {B[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {B[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {B[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {B[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {B[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {B[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {B[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {B[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {B[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {B[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {B[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {opcode[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {opcode[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {opcode[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {opcode[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {opcode[0]}]
set_timing_derate -early 0.9500
set_timing_derate -late 1.0500
###############################################################################
# Design Rules
###############################################################################
set_max_transition 0.7500 [current_design]
set_max_capacitance 0.2000 [current_design]
set_max_fanout 10.0000 [current_design]
