module ALU #(parameter WIDTH=32)(
  input logic [WIDTH-1:0] A,B,
  input logic [4:0] opcode,
  output logic [(2*WIDTH)-1:0] product,
  output logic [WIDTH-1:0] result,quotient,remainder,
  output logic carry,borrow,zero,negative,overflow,div_zero
);
  localparam ADD  = 5'b00000;
  localparam SUB  = 5'b00001;
  localparam AND  = 5'b00010;
  localparam OR   = 5'b00011;
  localparam XOR  = 5'b00100;
  localparam NOT_A = 5'b00101;
  localparam RIGHT_SHIFT=5'b00110;
  localparam LEFT_SHIFT=5'b00111;
  localparam ARITHMETIC_RIGHT_SHIFT=5'b01000;
  localparam INC_A =5'b01001;
  localparam DEC_A =5'b01010;
  localparam NAND = 5'b01011;
  localparam NOR = 5'b01100;
  localparam XNOR= 5'b01101;
  localparam SLT= 5'b01110;
  localparam PASS_B=5'b01111;
  localparam MUL=5'b10000;
  localparam DIV=5'b10001;
  
  // PARAMETERIZED UNSIGNED RADIX-4 BOOTH MULTIPLIER
  localparam int MUL_WIDTH = (2 * WIDTH) + 2;
  // Extra Booth group is required for unsigned multiplication.
  // WIDTH=64 -> 33 partial products.
  localparam int NUM_PP = (WIDTH / 2) + 1;
  localparam int LEVELS = $clog2(NUM_PP);
  initial begin
    if (WIDTH % 2 != 0)
      $error("ALU WIDTH must be even for the radix-4 multiplier.");
  end
  // Extended multiplicand
  logic signed [MUL_WIDTH-1:0] booth_A;
  logic signed [MUL_WIDTH-1:0] booth_2A;
  // Extended multiplier bits used by Booth encoding.
  // Format:
  // {two leading zeros, B, one trailing zero}
  // The trailing zero represents Booth's y[-1].
  logic [WIDTH+2:0] booth_B;
  // Radix-4 Booth partial products
  logic signed [MUL_WIDTH-1:0] partial_product [0:NUM_PP-1];
  // Balanced reduction tree
  logic signed [MUL_WIDTH-1:0] reduction [0:LEVELS][0:NUM_PP-1];
  // Final multiplier result
  logic [(2*WIDTH)-1:0] mul_product;
  integer m;

  // RADIX-4 BOOTH PARTIAL PRODUCT GENERATION
  always_comb begin
    booth_A  = $signed({2'b00, A});
    booth_2A = booth_A <<< 1;

    // Add leading zeros for unsigned Booth encoding
    // and one trailing zero for y[-1].
    booth_B = {2'b00, B, 1'b0};

    for (m = 0; m < NUM_PP; m = m + 1) begin

      case (booth_B[2*m+2 -: 3])

        // 000 / 111 -> 0
        3'b000,
        3'b111:
          partial_product[m] = '0;

        // 001 / 010 -> +A
        3'b001,
        3'b010:
          partial_product[m] =
              booth_A <<< (2*m);

        // 011 -> +2A
        3'b011:
          partial_product[m] =
              booth_2A <<< (2*m);

        // 100 -> -2A
        3'b100:
          partial_product[m] =
              (-booth_2A) <<< (2*m);

        // 101 / 110 -> -A
        3'b101,
        3'b110:
          partial_product[m] =
              (-booth_A) <<< (2*m);

        default:
          partial_product[m] = '0;

      endcase

    end
  end

    
  // BALANCED PARTIAL PRODUCT REDUCTION TREE
    

  genvar level;
  genvar node;

  generate

    // Initial level
    for (node = 0; node < NUM_PP; node = node + 1) begin : INIT_TREE

      assign reduction[0][node] =
          partial_product[node];

    end

    // Each level approximately halves the number of values.
    for (level = 0; level < LEVELS; level = level + 1) begin : REDUCE_LEVEL

      localparam int PREV_COUNT =
          (NUM_PP + (1 << level) - 1) >> level;

      localparam int CUR_COUNT =
          (NUM_PP + (1 << (level + 1)) - 1) >> (level + 1);

      for (node = 0; node < NUM_PP; node = node + 1) begin : REDUCE_NODE

        if (node < CUR_COUNT) begin : ACTIVE_NODE

          if ((2*node + 1) < PREV_COUNT) begin : HAS_PAIR

            assign reduction[level+1][node] =
                reduction[level][2*node] +
                reduction[level][2*node+1];

          end
          else begin : PASS_VALUE

            assign reduction[level+1][node] =
                reduction[level][2*node];

          end

        end
        else begin : UNUSED_NODE

          assign reduction[level+1][node] = '0;

        end

      end

    end
  endgenerate
  // Final reduced product
  assign mul_product =
      reduction[LEVELS][0][(2*WIDTH)-1:0];
  // PARAMETERIZED RADIX-4 RESTORING DIVIDER

  localparam int DIV_STAGES = WIDTH / 2;
  localparam int DIV_WIDTH  = WIDTH + 2;

  // Remainder after every radix-4 stage
  logic [DIV_WIDTH-1:0] div_remainder [0:DIV_STAGES];

  // Two quotient bits generated by each stage
  logic [1:0] div_quotient_digit [0:DIV_STAGES-1];

  // Final internal divider outputs
  logic [WIDTH-1:0] div_quotient;
  logic [WIDTH-1:0] div_final_remainder;

  // Precomputed divisor multiples
  logic [DIV_WIDTH-1:0] div_B;
  logic [DIV_WIDTH-1:0] div_2B;
  logic [DIV_WIDTH-1:0] div_3B;

  integer d;
  // RADIX-4 DIVISION
  always_comb begin
    // Extend divisor
    div_B  = {{2{1'b0}}, B};
    div_2B = div_B << 1;
    div_3B = div_2B + div_B;
    // Default remainder values
    for (d = 0; d <= DIV_STAGES; d = d + 1)
      div_remainder[d] = '0;
    // Default values
    for (d = 0; d < DIV_STAGES; d = d + 1)
      div_quotient_digit[d] = 2'b00;
    // Division only when B != 0
    if (B != '0) begin
      for (d = 0; d < DIV_STAGES; d = d + 1) begin
        // Bring down two dividend bits.
        // WIDTH = 64:
        // d = 0  -> A[63:62]
        // d = 1  -> A[61:60]
        // d = 31 -> A[1:0]
        div_remainder[d+1] =
            (div_remainder[d] << 2) |
            A[WIDTH-1-(2*d) -: 2];
        // Determine quotient digit.
        // q = 3
        if (div_remainder[d+1] >= div_3B) begin
          div_remainder[d+1] =
              div_remainder[d+1] - div_3B;
          div_quotient_digit[d] = 2'b11;
        end
        // q = 2
        else if (div_remainder[d+1] >= div_2B) begin
          div_remainder[d+1] =
              div_remainder[d+1] - div_2B;
          div_quotient_digit[d] = 2'b10;
        end
        // q = 1
        else if (div_remainder[d+1] >= div_B) begin
          div_remainder[d+1] =
              div_remainder[d+1] - div_B;
          div_quotient_digit[d] = 2'b01;
        end
        // q = 0
        else begin
          div_quotient_digit[d] = 2'b00;
        end
      end
    end
    // Reconstruct the quotient from the radix-4 digits
    div_quotient = '0;
    if (B != '0) begin
      for (d = 0; d < DIV_STAGES; d = d + 1) begin
        div_quotient[WIDTH-1-(2*d) -: 2] =
            div_quotient_digit[d];
      end
    end
    // Final remainder
    div_final_remainder = '0;
    if (B != '0)
      div_final_remainder =
          div_remainder[DIV_STAGES][WIDTH-1:0];
  end

  always_comb begin
    result   = '0;
    product  = '0;
    quotient = '0;
    remainder = '0;
    carry    = 1'b0;
    borrow   = 1'b0;
    div_zero = 1'b0;
    
    case(opcode)
      ADD:begin //ADDITION
        {carry,result} = {1'b0,A} + {1'b0,B};
      end
      SUB:begin //SUBTRACT
        result = A - B;
        borrow = (A < B);
      end
      AND:begin //AND
        result=A&B;
      end
      OR:begin //OR
        result=A|B;
      end
      XOR:begin //XOR
        result=A^B;
      end
      NOT_A:begin //NOT_A
        result=~A;
      end
      RIGHT_SHIFT:begin //RIGHT_SHIFT
        result=A>>B;
      end
      LEFT_SHIFT:begin //LEFT_SHIFT
        result=A<<B;
      end
      ARITHMETIC_RIGHT_SHIFT:begin //ARITHMETIC_RIGHT_SHIFT
        result=$signed(A)>>>B;
      end
      INC_A:begin //INC_A
        {carry,result} = {1'b0,A} + {{WIDTH{1'b0}},1'b1};
      end
      DEC_A:begin //DEC_A
        result = A - 1;
    	borrow = (A < 1);
      end
      NAND:begin //NAND
        result=~(A&B);
      end
      NOR:begin //NOR
        result=~(A|B);
      end
      XNOR:begin //XNOR
        result=~(A^B);
      end
      SLT:begin //SLT
        if ($signed(A) < $signed(B))
            result = 1;
        else
            result = 0;
      end
      PASS_B:begin //PASS_B
        result=B;
      end
      MUL:begin // MUL: result is not used; full product is available in product
        product = mul_product;
      end
      DIV:begin //DIV: result is not used; quotient and remainder are separate outputs
        // Radix-4 restoring divider
        quotient  = div_quotient;
        remainder = div_final_remainder;
        if (B == '0)
          div_zero = 1'b1;
      end
    endcase
  end
  assign zero =(result == '0);
  assign negative = result[WIDTH-1];
  assign overflow =
    // ADD overflow
    ((opcode == ADD) && ((A[WIDTH-1] & B[WIDTH-1] & ~result[WIDTH-1]) | (~A[WIDTH-1] & ~B[WIDTH-1] & result[WIDTH-1])))
    ||
    // SUB overflow
    ((opcode == SUB) && ((~A[WIDTH-1] & B[WIDTH-1] & result[WIDTH-1]) | (A[WIDTH-1] & ~B[WIDTH-1] & ~result[WIDTH-1])))
    ||
    // INC overflow
    ((opcode == INC_A) && (~A[WIDTH-1] & result[WIDTH-1]))
    ||
    // DEC overflow
    ((opcode == DEC_A) && (A[WIDTH-1] & ~result[WIDTH-1]));
endmodule
